"""empty message

Revision ID: 849774125e32
Revises: 749692e2daec
Create Date: 2019-09-22 21:54:28.443387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849774125e32'
down_revision = '749692e2daec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('phone', table_name='emp_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone', 'emp_info', ['phone'], unique=True)
    # ### end Alembic commands ###
