"""添加表animal

Revision ID: 506dbbac31a9
Revises: a768c4710094
Create Date: 2019-09-20 19:30:16.238189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506dbbac31a9'
down_revision = 'a768c4710094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('color', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animal')
    # ### end Alembic commands ###
